// Classic Plus: rule 1's card types and frame types, and the rule steps a card
// can hit with the copy limit each one sets. Shared by the built-in format
// (server/utils/rule-formats.ts) and the classification scripts
// (scripts/classic-plus/), which turn the steps into the Classic Plus banlist.
// Dependency-free on purpose: the scripts import it under plain Node type
// stripping.
//
// See docs/adr/0022-classic-plus-format.md.

export interface ClassicPlusStep {
  /** Rule and sub-step as the rulebook numbers it, e.g. `3.2` or `9a`. */
  code: string
  maxCopies: 0 | 1 | 2
  /** For review.csv and the script's summary. */
  label: string
}

/**
 * Every step that puts cards on the banlist, in rulebook order. Rule 1 is not
 * listed: it is a card-type filter. A card's banlist status is the strictest
 * limit of its steps. The numbers are the rulebook's adjustable values
 * ("Stellschrauben") — changing one here and rerunning combine.ts changes
 * the format without classifying anything again.
 */
export const CLASSIC_PLUS_STEPS: ClassicPlusStep[] = [
  { code: '2', maxCopies: 0, label: 'Rule 2: mentions Synchro, Xyz, Pendulum or Link' },
  { code: '3.1', maxCopies: 0, label: 'Rule 3.1: floodgate comparing both fields' },
  { code: '3.2', maxCopies: 2, label: 'Rule 3.2: floodgate the opponent can play around' },
  { code: '3.3', maxCopies: 1, label: 'Rule 3.3: floodgate on a card property' },
  { code: '3.4', maxCopies: 0, label: 'Rule 3.4: floodgate' },
  { code: '4', maxCopies: 0, label: 'Rule 4: hand trap' },
  { code: '5', maxCopies: 1, label: 'Rule 5: draw' },
  { code: '6a', maxCopies: 1, label: 'Rule 6a: effect damage' },
  { code: '6b', maxCopies: 1, label: 'Rule 6b: multiplies battle damage' },
  { code: '7a', maxCopies: 1, label: 'Rule 7a: takes control' },
  { code: '7b', maxCopies: 1, label: 'Rule 7b: revives from GY or banishment' },
  { code: '7c', maxCopies: 1, label: 'Rule 7c: Extra Deck summon without full materials' },
  { code: '7d', maxCopies: 1, label: 'Rule 7d: Fusion material from the Deck' },
  { code: '8', maxCopies: 1, label: 'Rule 8: mass removal' },
  { code: '9a', maxCopies: 1, label: 'Rule 9a: protection from card effects' },
  { code: '9b', maxCopies: 2, label: 'Rule 9b: protection from battle' },
  { code: '10', maxCopies: 1, label: 'Rule 10: negation' },
  { code: '11a', maxCopies: 1, label: 'Rule 11: denies a phase or Normal Summon once' },
  { code: '11b', maxCopies: 0, label: 'Rule 11: denies a phase or Normal Summon repeatedly' },
  { code: 'frequency', maxCopies: 0, label: 'Frequency modifier: limited effect usable twice per turn' },
  { code: 'stacking', maxCopies: 0, label: 'Stacking rule: protection plus multiplied battle damage' },
]

/** Steps the classifier may report (rule 2 and the two cross-cutting rules are applied by script). */
export const CLASSIC_PLUS_CLASSIFIER_CODES = CLASSIC_PLUS_STEPS
  .map(step => step.code)
  .filter(code => code !== '2' && code !== 'frequency' && code !== 'stacking')

/**
 * Rule 1 as the format's filter: card types the format editor can show and
 * keep (it doesn't keep frame types). Pendulum cards whose type doesn't say so
 * (e.g. "Spirit Monster") go on the banlist instead, see combine.ts.
 */
export const CLASSIC_PLUS_FORBIDDEN_TYPES = [
  'Synchro Monster',
  'Synchro Tuner Monster',
  'Synchro Pendulum Effect Monster',
  'XYZ Monster',
  'XYZ Pendulum Effect Monster',
  'Link Monster',
  'Pendulum Normal Monster',
  'Pendulum Effect Monster',
  'Pendulum Tuner Effect Monster',
  'Pendulum Flip Effect Monster',
  'Pendulum Effect Fusion Monster',
  'Pendulum Effect Ritual Monster',
]

/** Rule 1 by frame type (`catalog_card.frame_type`), which is exact; the scripts use it. */
export const CLASSIC_PLUS_FORBIDDEN_FRAME_TYPES = [
  'synchro',
  'xyz',
  'link',
  'normal_pendulum',
  'effect_pendulum',
  'ritual_pendulum',
  'fusion_pendulum',
  'synchro_pendulum',
  'xyz_pendulum',
]

/** Rule 2, applied to the English card text: a case-sensitive whole-word mention. */
export const CLASSIC_PLUS_RULE_2_PATTERN = /\b(?:Synchro|Xyz|XYZ|Link|Pendulum)\b/

/** The Classic Plus banlist (`server/utils/classic-plus-banlist.json`, generated by scripts/classic-plus/combine.ts). */
export interface ClassicPlusBanlist {
  forbidden: number[]
  limited: number[]
  semiLimited: number[]
}
